name: newsfragment_checker

on: [push, pull_request, label]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: pip
      - run: pip install .[changelog]

      - name: get added newsfragments
        if: ! contains(github.event.pull_request.labels.*.name, 'no changelog')
        run: towncrier check --compare-with origin/main

      - name: Print result
        run: echo "Newsfragment added"
