name: Publish Python distributions to TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Update package cache
        run: sudo apt-get -yq update
      - name: Install Deps for installing project
        run: pip install Sphinx coverage wheel
      - name: Fetch date for version bump
        run: echo "new_version=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
      - name: Replace version in setup.py
        run: sed -i '/[[:space:]]*version="[0-9]+(\.[0-9]+){2}"/s//version="${{ env.new_version }}"/' setup.py
      - name: Install Deps with pip
        run: pip install .
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
