name: Testing libcobblersignatures

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.py'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the tests
      run: |
        pytest --cache-clear --cov=libcobblersignatures tests/ && coverage xml
    # https://github.com/codacy/codacy-coverage-reporter-action
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
